// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoveTaskRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTaskRequest) Reset()         { *m = RemoveTaskRequest{} }
func (m *RemoveTaskRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTaskRequest) ProtoMessage()    {}
func (*RemoveTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_6260cb38b2b73b7e, []int{0}
}
func (m *RemoveTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTaskRequest.Unmarshal(m, b)
}
func (m *RemoveTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTaskRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTaskRequest.Merge(dst, src)
}
func (m *RemoveTaskRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTaskRequest.Size(m)
}
func (m *RemoveTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTaskRequest proto.InternalMessageInfo

func (m *RemoveTaskRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveTaskReply struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTaskReply) Reset()         { *m = RemoveTaskReply{} }
func (m *RemoveTaskReply) String() string { return proto.CompactTextString(m) }
func (*RemoveTaskReply) ProtoMessage()    {}
func (*RemoveTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_6260cb38b2b73b7e, []int{1}
}
func (m *RemoveTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTaskReply.Unmarshal(m, b)
}
func (m *RemoveTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTaskReply.Marshal(b, m, deterministic)
}
func (dst *RemoveTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTaskReply.Merge(dst, src)
}
func (m *RemoveTaskReply) XXX_Size() int {
	return xxx_messageInfo_RemoveTaskReply.Size(m)
}
func (m *RemoveTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTaskReply proto.InternalMessageInfo

func (m *RemoveTaskReply) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type TaskRequest struct {
	Namespace            string          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	JobName              string          `protobuf:"bytes,2,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Spec                 string          `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Args                 *_struct.Struct `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_6260cb38b2b73b7e, []int{2}
}
func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (dst *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(dst, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TaskRequest) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *TaskRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *TaskRequest) GetArgs() *_struct.Struct {
	if m != nil {
		return m.Args
	}
	return nil
}

type TaskReply struct {
	MasterId             string          `protobuf:"bytes,1,opt,name=masterId,proto3" json:"masterId,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	JobName              string          `protobuf:"bytes,3,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Spec                 string          `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Args                 *_struct.Struct `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaskReply) Reset()         { *m = TaskReply{} }
func (m *TaskReply) String() string { return proto.CompactTextString(m) }
func (*TaskReply) ProtoMessage()    {}
func (*TaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_6260cb38b2b73b7e, []int{3}
}
func (m *TaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReply.Unmarshal(m, b)
}
func (m *TaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReply.Marshal(b, m, deterministic)
}
func (dst *TaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReply.Merge(dst, src)
}
func (m *TaskReply) XXX_Size() int {
	return xxx_messageInfo_TaskReply.Size(m)
}
func (m *TaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReply proto.InternalMessageInfo

func (m *TaskReply) GetMasterId() string {
	if m != nil {
		return m.MasterId
	}
	return ""
}

func (m *TaskReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskReply) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *TaskReply) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *TaskReply) GetArgs() *_struct.Struct {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*RemoveTaskRequest)(nil), "RemoveTaskRequest")
	proto.RegisterType((*RemoveTaskReply)(nil), "RemoveTaskReply")
	proto.RegisterType((*TaskRequest)(nil), "TaskRequest")
	proto.RegisterType((*TaskReply)(nil), "TaskReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServerClient is the client API for TaskServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServerClient interface {
	AddTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskReply, error)
	RemoveTask(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*RemoveTaskReply, error)
}

type taskServerClient struct {
	cc *grpc.ClientConn
}

func NewTaskServerClient(cc *grpc.ClientConn) TaskServerClient {
	return &taskServerClient{cc}
}

func (c *taskServerClient) AddTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskReply, error) {
	out := new(TaskReply)
	err := c.cc.Invoke(ctx, "/TaskServer/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServerClient) RemoveTask(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*RemoveTaskReply, error) {
	out := new(RemoveTaskReply)
	err := c.cc.Invoke(ctx, "/TaskServer/RemoveTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServerServer is the server API for TaskServer service.
type TaskServerServer interface {
	AddTask(context.Context, *TaskRequest) (*TaskReply, error)
	RemoveTask(context.Context, *RemoveTaskRequest) (*RemoveTaskReply, error)
}

func RegisterTaskServerServer(s *grpc.Server, srv TaskServerServer) {
	s.RegisterService(&_TaskServer_serviceDesc, srv)
}

func _TaskServer_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServerServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskServer/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServerServer).AddTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServer_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServerServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskServer/RemoveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServerServer).RemoveTask(ctx, req.(*RemoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TaskServer",
	HandlerType: (*TaskServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskServer_AddTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _TaskServer_RemoveTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_grpc_6260cb38b2b73b7e) }

var fileDescriptor_grpc_6260cb38b2b73b7e = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x9b, 0x34, 0xb4, 0xcd, 0x2d, 0xe2, 0xc7, 0x0b, 0x51, 0xd4, 0xa1, 0xb2, 0x84, 0x54,
	0x09, 0xc9, 0x91, 0x0a, 0x2f, 0x50, 0x36, 0x16, 0x86, 0x84, 0x89, 0xcd, 0x71, 0x2e, 0x51, 0x68,
	0x83, 0x83, 0xed, 0x54, 0xe2, 0x05, 0x78, 0x00, 0x9e, 0x18, 0xc5, 0xfd, 0x49, 0xd4, 0x76, 0xe8,
	0xe6, 0x7b, 0x6c, 0x9d, 0xfb, 0x1d, 0x1f, 0x80, 0x5c, 0x55, 0x82, 0x55, 0x4a, 0x1a, 0x19, 0x4e,
	0x72, 0x29, 0xf3, 0x15, 0x46, 0x76, 0x4a, 0xeb, 0x8f, 0x48, 0x1b, 0x55, 0x0b, 0xb3, 0xb9, 0xa5,
	0x0b, 0xb8, 0x8d, 0xb1, 0x94, 0x6b, 0x7c, 0xe3, 0x7a, 0x19, 0xe3, 0x77, 0x8d, 0xda, 0x90, 0x09,
	0xf8, 0x5f, 0xbc, 0x44, 0x5d, 0x71, 0x81, 0x81, 0x33, 0x75, 0x66, 0x7e, 0xdc, 0x0a, 0xe4, 0x0a,
	0xdc, 0x22, 0x0b, 0x5c, 0x2b, 0xbb, 0x45, 0x46, 0x23, 0xb8, 0xee, 0x5a, 0x54, 0xab, 0x9f, 0xc6,
	0xa0, 0xd0, 0x49, 0x2d, 0x04, 0x6a, 0x6d, 0x0d, 0x46, 0x71, 0x2b, 0xd0, 0x5f, 0x07, 0xc6, 0xe7,
	0xaf, 0x0b, 0x60, 0xf8, 0x29, 0xd3, 0x57, 0x5e, 0xe2, 0x76, 0xe7, 0x6e, 0x24, 0x04, 0x3c, 0x5d,
	0xa1, 0x08, 0xfa, 0x56, 0xb6, 0x67, 0xf2, 0x00, 0x1e, 0x57, 0xb9, 0x0e, 0xbc, 0xa9, 0x33, 0x1b,
	0xcf, 0xef, 0xd8, 0x26, 0x3c, 0xdb, 0x85, 0x67, 0x89, 0x0d, 0x1f, 0xdb, 0x47, 0xf4, 0xcf, 0x01,
	0xbf, 0x85, 0x0e, 0x61, 0x54, 0x72, 0x6d, 0x50, 0xbd, 0x64, 0x5b, 0x8a, 0xfd, 0x7c, 0x98, 0xb9,
	0x0b, 0xd5, 0x3f, 0x0d, 0xe5, 0x9d, 0x80, 0xba, 0x38, 0x03, 0x6a, 0x5e, 0x00, 0x34, 0x4c, 0x09,
	0xaa, 0x35, 0x2a, 0x72, 0x0f, 0xc3, 0x45, 0x96, 0x35, 0x02, 0xb9, 0x64, 0x9d, 0x4f, 0x0b, 0x81,
	0xed, 0xc9, 0x69, 0x8f, 0x3c, 0x01, 0xb4, 0x1d, 0x10, 0xc2, 0x8e, 0x3a, 0x0d, 0x6f, 0xd8, 0x41,
	0x49, 0xb4, 0xf7, 0x3c, 0x78, 0xf7, 0x0c, 0xd7, 0xcb, 0x74, 0x60, 0x49, 0x1e, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xd5, 0x2b, 0xed, 0x7f, 0x37, 0x02, 0x00, 0x00,
}
